version: 2
jobs:

  test-php74:
    docker:
      - image: circleci/php:7.4-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install PHPUnit
          command: |
            composer require mmoreram/symfony-bundle-dependencies:^2.2 --no-update

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --prefer-lowest --no-suggest
            php vendor/bin/phpunit --testsuite=with-bundle-dependencies

  test-php80-no-dependencies:
    docker:
      - image: circleci/php:8.0-cli

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit --testsuite=no-bundle-dependencies

workflows:
  version: 2
  test:
    jobs:
      - test-php74
      - test-php80-no-dependencies